import whatsall.whatsall as whatsall
import selenium
import time
import os
whatsall.start()
f1=open("phone.txt","r")
num=f1.readlines(1)
new_numbers = [];

for n in num:

  new_numbers.append(int(n))

num = new_numbers
num=','.join(str(i) for i in num)
num2=f1.readlines(2)
print(num)

whatsall.number(num,'2420') #add as many numbers as you want in list
whatsall.message(num2) #add as many messages as you wish in the list
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
whatsall.send_message()
print("100 Message sent finished")




